{
 "title": "Logloss & AUC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Метрика logloss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "logloss_gaude", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Метрика AUC ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "auc_gaude", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Номер пакета данных",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count_batch", "legendFormat": "__auto" }
   ]
  }
 ]
}